export const countries = [
  { id: 1, name: 'Chile', iso2: 'CL' },
  { id: 2, name: 'Argentina', iso2: 'AR' },
  { id: 3, name: 'Uruguay', iso2: 'UY' },
  { id: 4, name: 'Paraguay', iso2: 'PY' },
  { id: 5, name: 'Bolivia', iso2: 'BO' },
  { id: 6, name: 'Peru', iso2: 'PE' },
  { id: 7, name: 'Ecuador', iso2: 'EC' },
  { id: 8, name: 'Colombia', iso2: 'CO' },
  { id: 9, name: 'Venezuela', iso2: 'VE' },
  { id: 10, name: 'Guyana', iso2: 'GY' },
  { id: 11, name: 'Suriname', iso2: 'SR' },
  { id: 12, name: 'French Guiana', iso2: 'GF' },
  { id: 13, name: 'Brazil', iso2: 'BR' },
  { id: 14, name: 'Panama', iso2: 'PA' },
  { id: 15, name: 'Costa Rica', iso2: 'CR' },
  { id: 16, name: 'Nicaragua', iso2: 'NI' },
  { id: 17, name: 'Honduras', iso2: 'HN' },
  { id: 18, name: 'El Salvador', iso2: 'SV' },
  { id: 19, name: 'Guatemala', iso2: 'GT' },
  { id: 20, name: 'Belize', iso2: 'BZ' },
  { id: 21, name: 'Mexico', iso2: 'MX' },
  { id: 22, name: 'Cuba', iso2: 'CU' },
  { id: 23, name: 'Haiti', iso2: 'HT' },
  { id: 24, name: 'Dominican Republic', iso2: 'DO' },
  { id: 25, name: 'Jamaica', iso2: 'JM' }
];